# Generated by Django 4.1.3 on 2022-11-20 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=30)),
                ('categoria', models.CharField(max_length=30)),
                ('precio', models.IntegerField(default=0)),
                ('cantidad', models.IntegerField(default=0)),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
